name: 'Release FoundryVTT Package'
author: 'Joe Spandrusyszyn (illandril)'
description: 'Pushes a new FoundryVTT package release to FoundryVTT.com'
branding:
  icon: 'package'
  color: 'gray-dark'
inputs:
  package-release-token:
    description: 'The secret API token for the package'
    required: true
  manifest-url:
    description: 'The URL to the manfiest file for the version you are releasing'
    required: true
  dry-run:
    description: 'Send the dry-run parameter to the Package Release API'
    default: 'false'
outputs:
  response:
    description: 'The response received from the API.'
runs:
  using: 'node20'
  main: 'index.js'
