name: Issue / PR assignment

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  auto-assign:
    uses: ./.github/workflows/illandril-assign.yml
