on:
  workflow_call:
    inputs:
      node-version:
        type: number
        default: 20
    secrets:
      GITHUB_TOKEN:
        required: true
      PACKAGE_RELEASE_TOKEN:
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}

      - name: Install npm dependencies
        run: npm ci --ignore-scripts

      - name: Run validation
        run: npm run validate

  publish-module:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read
    steps:
      - name: Extract version number
        id: version
        uses: actions/github-script@v7
        with:
          script: return context.ref.substring(11);
          result-encoding: string

      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}

      - name: Install npm dependencies
        run: npm ci --ignore-scripts

      - name: Build
        run: npm run build

      - name: Bundle
        run: cd dist; zip -r module.zip *; cd -

      - name: Publish
        id: create_version_release
        uses: ncipollo/release-action@v1
        with:
          name: ${{ steps.version.outputs.result }}
          generateReleaseNotes: true
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: './dist/module.json, ./dist/module.zip'
          tag: ${{ github.ref_name }}

      - name: Release
        uses: illandril/FoundryVTT-package-release-action@v1
        with:
          package-release-token: ${{ secrets.PACKAGE_RELEASE_TOKEN }}
          manifest-url: "https://github.com/${{ github.repository }}/releases/download/v${{ steps.version.outputs.result }}/module.json"
